In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,4,5,56,7])
a

array([ 1,  2,  3,  4,  5, 56,  7])

In [6]:
a[5] = 7

In [7]:
a

array([1, 2, 3, 4, 5, 7, 7])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
##multidimensional array

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
a =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a[0,2] =12
a

array([[ 1,  2, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [14]:
a[:,2] =[1,1,1]

In [15]:
a

array([[1, 2, 1],
       [4, 5, 1],
       [7, 8, 1]])

In [16]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [17]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [18]:
np.random.seed(2)
np.random.randint(low=0, high =100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
a+2

array([2, 3, 4, 5, 6])

In [21]:
b = (10+(a*2))**2 
b

array([100, 144, 196, 256, 324])

In [22]:
a/b

array([0.        , 0.00694444, 0.01020408, 0.01171875, 0.01234568])

In [23]:
a>b

array([False, False, False, False, False])

In [24]:
a[a<b]

array([0, 1, 2, 3, 4])

In [25]:
a.max()

np.int64(4)

In [26]:
a.sum()

np.int64(10)

***Multiplication***

In [102]:
def vector_vector_mul(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i]*v[i]
    return result

In [92]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [93]:
u.shape

(4,)

In [94]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [78]:
v.shape

(4,)

In [79]:
vector_vector_mul(u,v)

np.float64(14.0)

In [80]:
u.dot(v)

np.int64(14)

**Matrix Vector Multiplication**

In [103]:
def matrix_vector_mul(U,v):
    assert U.shape[1] == v.shape[0]

    n = U.shape[0]
    result = np.zeros(n)
    for i in range(n):
        result[i] = vector_vector_mul(U[i]*v)
    return result

In [99]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
u.shape

(3, 4)

In [100]:
v = np.array([
    [1],
    [0.5],
    [2],
    [1]
])
v.shape

(4, 1)

In [104]:
matrix_vector_mul(u,v)

TypeError: vector_vector_mul() missing 1 required positional argument: 'v'

(3, 4)

AttributeError: 'list' object has no attribute 'shape'