In [41]:
import numpy as np

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [45]:
a = np.array([1,2,3,4,5,56,7])
a

array([ 1,  2,  3,  4,  5, 56,  7])

In [46]:
a[5] = 7

In [47]:
a

array([1, 2, 3, 4, 5, 7, 7])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
##multidimensional array

In [52]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
a =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a[0,2] =12
a

array([[ 1,  2, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [57]:
a[:,2] =[1,1,1]

In [58]:
a

array([[1, 2, 1],
       [4, 5, 1],
       [7, 8, 1]])

In [63]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [65]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [67]:
np.random.seed(2)
np.random.randint(low=0, high =100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [68]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [69]:
a+2

array([2, 3, 4, 5, 6])

In [71]:
b = (10+(a*2))**2 
b

array([100, 144, 196, 256, 324])

In [72]:
a/b

array([0.        , 0.00694444, 0.01020408, 0.01171875, 0.01234568])

In [73]:
a>b

array([False, False, False, False, False])

In [74]:
a[a<b]

array([0, 1, 2, 3, 4])

In [78]:
a.max()

np.int64(4)

In [81]:
a.sum()

np.int64(54)